added login to api logic
shyluthomas/Event-manager-ui pull request #2
Opened 2024-02-22 17:32 UTC by BlesyMathew

Signed-off-by: BLESSY MATHEW <74411288+BlesyMathew@users.noreply.github.com>

2024-02-26 22:29 UTC, shyluthomas requested changes

2024-02-26 22:29 UTC, shyluthomas commented on src/components/layouts/authLayout.tsx
> +        backgroundColor: "black",
inline style

2024-02-26 22:29 UTC, shyluthomas commented on src/components/Modal/CommonModal.tsx
> +  console.log("modalll", status);
Remove console

2024-02-26 22:29 UTC, shyluthomas commented on src/components/layouts/ModalHOC.tsx
> +  console.log("modalMessage", modalMessage);
console

2024-02-26 22:29 UTC, shyluthomas commented on src/components/layouts/authLayout.tsx
> +// import { Toaster } from "../ui/sonner";
comments

2024-02-26 22:29 UTC, shyluthomas commented on src/components/layouts/fullLayout.tsx
> +                    helpers.removeAuthToken();
do not do logic in components, do saga fn and dispatch here

2024-02-26 22:29 UTC, shyluthomas commented on src/pages/user/newUser.tsx
> +            <ModalHOC />
Add this HOC in Layout component: ie, you can use in whole app

2024-02-26 22:29 UTC, shyluthomas commented on src/pages/user/newUser.tsx
> +                {/* <Label htmlFor="roleId">Role ID</Label> */}
remove comments

2024-02-26 22:29 UTC, shyluthomas commented on src/pages/user/userLogin.tsx
> +  console.log("username", username);
console and comments

2024-02-26 22:29 UTC, shyluthomas commented on src/store/saga/mainSaga.ts
> +      helpers.setAuthToken(response.data.token);
you need to add yield for this fn call

2024-02-26 22:29 UTC, shyluthomas commented on src/store/saga/mainSaga.ts
> +    console.log("first");
what the fck

2024-02-26 22:29 UTC, shyluthomas commented on src/utils/helpers.ts
> +    sessionStorage.removeItem("accessToken");
it should async fn

2024-02-27 04:05 UTC, BlesyMathew commented on src/components/layouts/authLayout.tsx
> +        backgroundColor: "black",
this is the outdated code mahn

2024-02-27 20:19 UTC, shyluthomas approved these changes

2024-02-27 20:20 UTC, merged